# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-01-17 23:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='NutritionFact',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name', models.CharField(max_length=255)),
                ('servings_per_container', models.IntegerField()),
                ('serving_size_g', models.IntegerField()),
                ('calories_kcal', models.IntegerField()),
                ('calories_from_fat_kcal', models.IntegerField()),
                ('total_fat_g', models.IntegerField()),
                ('sodium_mg', models.IntegerField()),
                ('total_carbs_g', models.IntegerField()),
            ],
        ),
    ]
