# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-01-18 17:43
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app2', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='nutritionfact',
            options={'ordering': ['product_name']},
        ),
    ]
