---
  - name: Install Django
    apt: name={{item}} state=installed
    with_items:
      - python-pip
      - python-dev
      - python3-dev
      - virtualenvwrapper
      - postgresql-9.3
      - postgresql-client-9.3
      - libpq-dev

  - name: Setup Python virtualenv
    command: mkvirtualenv -a /vagrant -r /vagrant/requirements.txt --python=`which python3` djfoundation1
