---
  - name: Install Django
    apt: name={{item}} state=installed
    with_items:
      - python-pip
      - python-dev
      - python3-dev
      - virtualenvwrapper
      - postgresql-9.3
      - postgresql-client-9.3
      # libpq-dev needed to compile python-psycopg2 PIP module
      - libpq-dev
      # python-psycopg2 needed for Ansible module, not Django
      - python-psycopg2

  - name: Add vagrant user to PostgreSQL
    become: yes
    become_user: postgres
    postgresql_user: name=vagrant role_attr_flags=LOGIN

  - name: Create Django database
    become: yes
    become_user: postgres
    postgresql_db: name=djsite owner=vagrant
